# Generated by Django 5.2.8 on 2025-11-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='catalog/')),
                ('available', models.BooleanField(default=True)),
                ('compatibility', models.CharField(choices=[('quest', 'Quest'), ('pico', 'Pico'), ('universal', 'Универсальные')], default='universal', max_length=20)),
            ],
        ),
    ]
